version: '3'

services:
  db:
    build: ./db/
    container_name: db
    ports: 
      - "9906:3306"
  web:
    build: ./web/
    container_name: web
    depends_on:
      - db
    ports:
      - "8080:80"
    stdin_open: true
    tty: true