version: '3'

services:
  db:
    image: onekill0503/db-data:latest
    ports: 
      - "9906:3306"
    networks:
      - default
  web:
    image: onekill0503/web-data:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    stdin_open: true
    tty: true